### ISSUE TITLE
[FEAT] Trim dead code in codegen

### ISSUE THREAD

**Issue by grilme99** [red-blox/zap#22]
## Describe your feature

Codegen currently has a lot of dead code if network definition files don't define enough variations of events. This makes linters upset because they flag unused functions and variables.

## Alternatives

A simple workaround for this issue would be to include comments at the top of the generated code to silence Selene and the Luau linter. However, this isn't ideal and the better solution is to actually trim dead code.

**Comment by jackdotink** [comment]
We will definitely be adding the comments to ignore dead code specifically. The way I view things like this (formatting, dead code elimination, etc) is that there are other programs that do this already like darklua and the luau compiler. If we can do it fairly easily then it's nice to have, otherwise we'll have to leave it to those other programs.

Determining dead code in particular is somewhat difficult for us - we will trim unused types as those are not eliminated by luau's dead code elimination step.

**Comment by sasial-dev** [comment]
Completed in `0.3.1` based upon @jackdotink's comment above.
